const SPECIAL_STRUCTURE_NODES = new Set([
  "logic.if_subflow",
  "logic.for_each_subflow",
  "logic.while_subflow",
]);

// Node implementations present in the recovered JS engine. Python/Notebook custom
// code is intentionally excluded: those nodes contain Python source in the current
// shared catalog and must stay on Python until a runtime-neutral custom-code model exists.
export const JAVASCRIPT_SUPPORTED_NODE_TYPES = new Set([
  "analysis.ter_matrix",
  "convert.json_parse",
  "convert.json_stringify",
  "convert.table_to_csv",
  "convert.table_to_records",
  "convert.to_boolean",
  "convert.to_number",
  "convert.to_table",
  "convert.to_text",
  "io.export_csv",
  "io.read_csv",
  "io.read_csv_batch",
  "io.read_image",
  "io.read_json",
  "io.read_table",
  "io.read_text",
  "generate.empty_list",
  "generate.empty_table",
  "generate.random_table",
  "logic.for_range",
  "logic.if_rows",
  "logic.merge_rows",
  "logic.while_number",
  "pandas.describe",
  "pandas.drop_duplicates",
  "pandas.dropna",
  "pandas.fillna",
  "pandas.head",
  "pandas.query",
  "pandas.round",
  "pandas.sample",
  "pandas.sort_values",
  "pandas.tail",
  "plot.area",
  "plot.bar",
  "plot.box",
  "plot.heatmap",
  "plot.histogram",
  "plot.line",
  "plot.scatter",
  "pulse.combine_channels",
  "pulse.generate_oscillating_ramp",
  "pulse.generate_waveform",
  "pulse.segment_measurement",
  "python.len",
  "python.print",
  "python.round",
  "table.absolute",
  "table.concat",
  "table.difference",
  "table.filter_range",
  "table.group_aggregate",
  "table.groupby_aggregate",
  "table.group_mean",
  "table.periodic_tail_mean",
  "table.periodic_window",
  "table.pivot",
  "table.rename_columns",
  "table.reset_index",
  "table.select_columns",
  "table.slice",
  "table.sort_index",
  "table.transpose",
  "ui.alert",
  "ui.input_dialog",
  "variable.get",
  "variable.set",
  ...SPECIAL_STRUCTURE_NODES,
]);


export function isJavascriptSupportedNodeType(nodeType: string): boolean {
  return nodeType === "workflow.group" || JAVASCRIPT_SUPPORTED_NODE_TYPES.has(nodeType);
}
